project:
  type: website
  output-dir: docs

website:
  title: "Data Visualization for Comparative Politics - Course Website"
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "Data Visualization for Comparative Politics | Fall 2023 | University of Mannheim"  
  sidebar:
    background: "#8399B0"
    logo: "images/hex_sticker.png"
    pinned: true
    align: center
    tools:
      - icon: slack
        href: https://datavis-fall2023.slack.com
        text: Slack
      - icon: bank
        href: https://ilias.uni-mannheim.de/goto.php?target=crs_1413212&client_id=ILIAS
        text: Ilias
      - icon: rocket
        href: https://www.dataquest.io/
        text: Dataquest
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: material.qmd
        text: Schedule
        
format:
  html:
    theme: 
      - default
      - css/theme.scss
    css: css/custom.css
    toc: true



