---
title: "Behaviour and Polarization"
subtitle: "Week9"
author: "David Schweizer"
date: "April 25, 2023"
date-format: long
institute: "University of Mannheim"
format: 
  revealjs:
    theme: serif
    slide-number: c/t #< collapsed/total
    footer: "The Politics of Climate Change | Spring 2023 | University of Mannheim"
editor: visual
---

## Plan for Today

-   Feedback \~ 5 min

-   Presentation \~ 20 - 25 min

-   Discussion of reading \~ 10 - 15 min

-   Group work \~ 45 - 55 min

## Feedback

-   Overall quite good (and constructive!), thank you.

-   As always: Split decision on group work. One last time!

-   Only IILIAS & too much effort for 5 ECTS.

-   Focus more on readings, input by lecturer, "interactive" discussions.

    -   But: This also requires effort from your side!

-   Please use available channels to communicate and get feedback during the semester!

## Presentation

-   Otteni, C., & Weisskircher, M. (2022). Global warming and polarization. Wind turbines and the electoral success of the greens and the populist radical right. European Journal of Political Research, 61(4), 1102-1122.

# Reading

## Discussion Mandatory Reading

-   How does it connect to other readings?

-   How does it connect to current events?

-   What do you take away for your own research agenda?

## Discussion Questions

-   To what extent does energy production in France, for example, where much energy consumption is covered by almost CO2 neutral nuclear power, contribute to social left-right polarization?

    -   Is the German case an exception?

    -   Are wind turbines an exception?

-   Under which circumstances is there no NIMBY effect?

    -   Which parties benefit? Is this still polarizing?

# Group Work

## NIMBY effect

-   **NIMBY** ([/ˈnɪmbi/](https://en.wikipedia.org/wiki/Help:IPA/English "Help:IPA/English"), or **nimby**),^[\[1\]](https://en.wikipedia.org/wiki/NIMBY#cite_note-1)^ an [acronym](https://en.wikipedia.org/wiki/Acronym "Acronym") for the phrase "**not in my back yard**",^[\[2\]](https://en.wikipedia.org/wiki/NIMBY#cite_note-2)[\[3\]](https://en.wikipedia.org/wiki/NIMBY#cite_note-3)^ is a characterization of opposition by residents to proposed developments in their local area, as well as support for strict land use regulations. It carries the connotation that such residents are only opposing the development because it is close to them and that they would tolerate or support it if it were built farther away.

    *Source: https://en.wikipedia.org/wiki/NIMBY*

## NIMBY effect

-   Prime example: Opposition against nuclear power plants.

-   Lately: Opposition against wind turbine projects (e.g., Bell et al., 2005; Ogilvie & Rootes, 2015; Toke, 2005).

-   Affects not only the protest, but also the electoral arena (Ahlfeldt & Maennig, 2012; Otteni & Weisskircher, Stokes, 2016).

## (Y)IMBY effect

-   **(Yes) in my back yard.**

-   Examples?

## Task (in groups of 3-4)

-   Brainstorm a research question related to the (N)IMBY effect (climate change context). Remember useful tools: ChatGPT, Connected Papers, Elicit, ResearchRabbit.

-   How could you test your hypotheses? What could be a possible research design?

-   What could be one potential policy implication? Specific climate project, local community's concerns, impacts on climate change mitigation, broader political context.

-   Add your ideas here: *Mural*

## Literature (1)

-   Ahlfeldt, G., & Maennig, W. (2012). Voting on a NIMBY facility: Proximity cost of an "iconic" stadium. *Urban Affairs Review*, *48*(2), 205-237.

-   Bell, D., Gray, T., & Haggett, C. (2005). The 'social gap'in wind farm siting decisions: explanations and policy responses. *Environmental politics*, *14*(4), 460-477.

-   Ogilvie, M., & Rootes, C. (2015). The impact of local campaigns against wind energy developments. *Environmental Politics*, *24*(6), 874-893.

## Literature (2)

-   Otteni, C., & Weisskircher, M. (2022). Global warming and polarization. Wind turbines and the electoral success of the greens and the populist radical right. *European Journal of Political Research*, *61*(4), 1102-1122.

-   Stokes, L. C. (2016). Electoral backlash against climate policy: A natural experiment on retrospective voting and local resistance to public policy. *American Journal of Political Science*, *60*(4), 958-974.

-   Toke, D. (2005). Explaining wind power planning outcomes:: some findings from a study in England and Wales. *Energy policy*, *33*(12), 1527-1539.
