---
title: "Natural Disasters and Political Accountability"
subtitle: "Week6"
author: "David Schweizer"
date: "March 21, 2023"
date-format: long
institute: "University of Mannheim"
format: 
  revealjs:
    theme: serif
    slide-number: c/t #< collapsed/total
    footer: "The Politics of Climate Change | Spring 2023 | University of Mannheim"
editor: visual
---

## Plan for Today

-   Orga: Term Paper & Presentations \~ 10 min

-   Last week & Discussion of readings \~ 25 min

-   First research question \~ 55 min

    -   Conceptualization

    -   Operationalization

    -   Justification of case selection

    -   Short presentations

-   Outlook next week

## Term Paper 

-   A first basic data analysis (descriptives, correlations, regression) is [desirable, but not necessary]{.underline}!

-   However, you need to:

    -   conceptualize,

    -   operationalize,

    -   justify your case selection,

    -   find suitable data and present how they are measured (e.g., survey questionnaires, codebook)

-   In principle, you should be able to perform the analysis!

## Term Paper - Example 

-    Climate protection \~ Democracy

-   Multiple ways to measure democracy. E.g., V-Dem, or Freedom House indicators. Why do you choose a specific indicator? Different conceptualizations of democracy?

    -   Robert Dahl's "polarchy": Free, fair, and competitive elections, but also civil freedoms

    -   Minimalist understanding as Joseph Schumpeter: Representation via competitive struggle in elections

## Presentations

-   Still missing preferences

-   Please give your preferences for papers to present the latest **until tomorrow!**

## Last Weeks

::: panel-tabset
## Public Opinion

-   Gender gap in wealthy but not in poor countries

    -   Men tend to attach greater material costs to mitigation

    -   Men tend to express more support for group-based dominance (correlated with climate skepticism)

-   Education as strong predictor for climate awareness

-   Predictors of climate risk perception differ depending on context

## Attitudes & Behavior

-   Natural disasters only with limited impact on

    -   voting for Green parties

    -   support for Green parties

    -   climate change salience

-   Direct exposure vs. indirect exposure? Long-term effects?
:::

# Readings

## Discussion Mandatory Readings

-   Who wrote the article? What's their background?

-   General summary of the article

-   Strengths & Weaknesses

-   How does it connect to other readings?

-   How does it connect to current events?

-   What do you take away for your own research agenda?

## Discussion Questions

-   Have you noticed the described retrospective considerations in your own political opinions/voting behavior, for example following the flooding of the Ahr valley?

-   Electoral reward for providing disaster relief, but not for investing in disaster prevention. Is shortsightedness unique to environmental disasters?

-   According to the theory of the responsive electorate, is there an incentive for politicians to act short-term and populist in order to keep their own popularity high?

# Research Question - Conceptualization, Operationalization, Case Selection

## Conceptualization

-   Clear and concise definitions of key concepts

    -   How have other scholars defined these concepts?

    -   Crucial for interpretation of results

-   Multiple dimensions? Which dimensions are relevant?

-   Keep in mind that your definitions might come with limitations

## Operationalization

-   How exactly do you plan to measure your concepts?

    -   This should include the variable and its measure

-   Multi-dimensional concepts can be measured with indexes, scales, as well as typologies

-   Previous research can help you with ideas for good (and bad) measurements

## Case Selection

-   **Motive of case selection:** Just convenience?

-   **Generalizability:** Can we apply lessons learned to other cases?

-   **Selection on the dependent variable:** Choosing cases because we know their outcome

-   If survey data: Representative sample? Are weights provided?

## Helpful Literature

-   Geddes, B. (1990). How the cases you choose affect the answers you get: Selection bias in comparative politics. *Political analysis*, *2*, 131-150.

-   King, G., Keohane, R. O., and Verba, S. (1994). Designing Social Inquiry: Scientific Inference in Qualitative Research. Princeton: Princeton University Press.

-   Powner, L. C. (2015). Empirical Research and Writing: A Political Science Student's Practical Guide. Los Angeles: Sage.

## Task for Today

-   In small groups, develop for your research question from last week the following:

    -   Conceptualization

    -   Operationalization

    -   Justification of case selection

-   Prepare a short presentation. We will discuss these steps on the basis of one or two presentations.

# Your Turn!

## Before the Easter Break

-   **Until tomorrow**: Indicate your paper preferences for the presentation

-   **Until 28.03**: Let me know by e-mail if you want to opt-in for the research proposal

-   Session before Easter (28.03.): Simple data management, descriptives & basic data analysis

## (Until) Next Week

-   BLOCK III - Political Parties (1): Succes and Impact of Green Parties. Add comments, discussion questions, etc. for the mandatory readings. Try Perusall:

    -   Abou-Chadi, T. (2016). Niche party success and mainstream party policy shifts--how green and radical right parties differ in their impact. British Journal of Political Science, 46(2), 417-436.

    -   Grant, Z. P., & Tilley, J. (2019). Fertile soil: explaining variation in the success of Green parties. West European Politics, 42(3), 495-516.
