---
title: "Party Responsiveness to Climate Change"
subtitle: "Week8"
author: "David Schweizer"
date: "April 18, 2023"
date-format: long
institute: "University of Mannheim"
format: 
  revealjs:
    theme: serif
    slide-number: c/t #< collapsed/total
    footer: "The Politics of Climate Change | Spring 2023 | University of Mannheim"
editor: visual
---

## Plan for Today

-   Time for anonymous feedback on ILIAS \~ 5-10 min

-   Presentation \~ 20 - 25 min

-   Discussion of reading \~ 15 min

-   Group work \~ 40 -45 min

# Feedback

# Presentation

# Reading

## Discussion Mandatory Reading

-   Who wrote the article? What's their background?

-   General summary of the article

-   Strengths & Weaknesses

-   How does it connect to other readings?

-   How does it connect to current events?

-   What do you take away for your own research agenda?

## Discussion Questions

-   How can political parties improve their response to environmental events like flooding to minimize negative electoral consequences?

-   To what degree do you expect the findings of this paper to be transferable to other countries, like Germany for example and other extreme weather events?

# Group Work

## Scenario (for ChatGPT)

-   Severe flood in Bavaria and Eastern Germany.

-   Energy security is an important topic due to the phase-out of nuclear energy.\
    \
    Target voter (no party ID):

```{=html}
<!-- -->
```
-   Average characteristics (e.g., average income).

-   Environmental protection is important to the voter, but she is concerned about too high transition costs.

## Task

-   Draft a press release for one of the following parties: Greens, FDP, CDU, or the AfD.
