<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>The Politics of Climate Change - Course Website - The Politics of Climate Change</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="css/custom.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">The Politics of Climate Change</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/hex_sticker.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main tools-wide">
    <a href="https://the-politics-of-cc.slack.com" title="Slack" class="sidebar-tool px-1"><i class="bi bi-slack"></i></a>
    <a href="https://ilias.uni-mannheim.de/goto.php?target=crs_1333381&amp;client_id=ILIAS" title="Ilias" class="sidebar-tool px-1"><i class="bi bi-bank"></i></a>
    <a href="https://www.perusall.com/" title="Perusall" class="sidebar-tool px-1"><i class="bi bi-book"></i></a>
</div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Home</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./syllabus.html" class="sidebar-item-text sidebar-link active">Syllabus</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./material.html" class="sidebar-item-text sidebar-link">Material</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#syllabus" id="toc-syllabus" class="nav-link active" data-scroll-target="#syllabus">Syllabus</a></li>
  <li><a href="#course-description" id="toc-course-description" class="nav-link" data-scroll-target="#course-description"><strong>Course description</strong></a></li>
  <li><a href="#course-requirements" id="toc-course-requirements" class="nav-link" data-scroll-target="#course-requirements">Course Requirements</a></li>
  <li><a href="#recommended-readings" id="toc-recommended-readings" class="nav-link" data-scroll-target="#recommended-readings">(Recommended) Readings</a></li>
  <li><a href="#organization-learning-resources" id="toc-organization-learning-resources" class="nav-link" data-scroll-target="#organization-learning-resources">Organization &amp; Learning Resources</a></li>
  <li><a href="#course-schedule" id="toc-course-schedule" class="nav-link" data-scroll-target="#course-schedule">Course Schedule</a></li>
  <li><a href="#course-schedule-and-reading-material" id="toc-course-schedule-and-reading-material" class="nav-link" data-scroll-target="#course-schedule-and-reading-material">Course Schedule and Reading Material</a>
  <ul class="collapse">
  <li><a href="#block-i-intro" id="toc-block-i-intro" class="nav-link" data-scroll-target="#block-i-intro"><strong>BLOCK I: INTRO</strong></a></li>
  <li><a href="#block-ii-political-behaviour" id="toc-block-ii-political-behaviour" class="nav-link" data-scroll-target="#block-ii-political-behaviour">BLOCK II: Political Behaviour</a></li>
  <li><a href="#block-iii-political-parties" id="toc-block-iii-political-parties" class="nav-link" data-scroll-target="#block-iii-political-parties">BLOCK III: Political Parties</a></li>
  <li><a href="#block-iv-climate-policies-behaviour-and-polarization" id="toc-block-iv-climate-policies-behaviour-and-polarization" class="nav-link" data-scroll-target="#block-iv-climate-policies-behaviour-and-polarization">BLOCK IV: Climate Policies, Behaviour, and Polarization</a></li>
  <li><a href="#block-v-challenges-of-climate-change" id="toc-block-v-challenges-of-climate-change" class="nav-link" data-scroll-target="#block-v-challenges-of-climate-change">BLOCK V: Challenges of Climate Change</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">The Politics of Climate Change</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="syllabus" class="level2">
<h2 class="anchored" data-anchor-id="syllabus">Syllabus</h2>
<p>Spring 2023</p>
<table class="table">
<tbody>
<tr class="odd">
<td>Proseminar:</td>
<td>PS Einführung in die Vergleichende Regierungslehre</td>
</tr>
<tr class="even">
<td>Time:</td>
<td>Tuesday, 15:30 – 17:00, February 14 to May 30, Cancelled dates: April 04, April 11</td>
</tr>
<tr class="odd">
<td>Place:</td>
<td>A 103 Seminarraum (B 6, 23-25 Bauteil A)</td>
</tr>
<tr class="even">
<td>Language:</td>
<td>English</td>
</tr>
<tr class="odd">
<td>Instructor:</td>
<td>David Schweizer, M.A., david.schweizer@uni-mannheim.de</td>
</tr>
<tr class="even">
<td>Office hours:</td>
<td>In-person (A 340) or via Zoom, Tue, 10:15 – 11:45, please make an appointment by e-mail</td>
</tr>
<tr class="odd">
<td>Course website:</td>
<td><a href="https://politics-of-climate-change.netlify.app" title="https://politics-of-climate-change.netlify.app">Link</a></td>
</tr>
</tbody>
</table>
</section>
<section id="course-description" class="level2">
<h2 class="anchored" data-anchor-id="course-description"><strong>Course description</strong></h2>
<p><strong><br>
</strong>Climate change is one of this century’s most significant challenges. Climate change mitigation and adaptation will require massive economic transformations and strongly affect other fields: infrastructure, health, agriculture, biodiversity, migration, and many more. How do political actors – parties, politicians, social movements, institutions, international organizations, etc. – react to and influence these transformations? And what about public opinion? Do citizens change their behavior (voting, consumption, etc.)? If yes, why and under what conditions? This course introduces students to theories and methods on the nexus of climate change and politics. It aims to equip the students with the necessary skills to formulate and pursue their own research questions at the intersection of climate change and politics. In addition, students will learn to engage critically with existing research and understand its implications. In doing so, the course will primarily focus on (quantitative) empirical research addressing party competition, political behavior, and policymaking.</p>
<p><strong>Seminar Goals:</strong></p>
<ul>
<li><p>Introducing concepts, definitions, and measurements in the field of climate change in political science research</p></li>
<li><p>Getting to know the recent literature and being able to critically engage with it</p></li>
<li><p>Being able to interpret the results of the analyses applied in the literature</p></li>
<li><p>Being able to present the core results and main take-aways of research articles - Identifying research questions and research designs at the intersection of climate change and politics</p></li>
<li><p>Formulating own research questions and conducting own research</p></li>
</ul>
</section>
<section id="course-requirements" class="level2">
<h2 class="anchored" data-anchor-id="course-requirements">Course Requirements</h2>
<p><strong>Participation:</strong></p>
<p>Attending the weekly sessions and reading assigned articles (mandatory) before class. Use Perusall to annotate articles collaboratively and exchange via Slack. (Of course, there is still also the discussion forum on ILIAS to post questions or discuss with your peers if you are stuck.) You are encouraged to also have a look at the further readings.</p>
<p><strong>Discussion questions for mandatory readings (Pass/Fail):</strong></p>
<p>Each week, students should submit a discussion question for at least one mandatory reading (via Perusall or ILIAS) at the latest on the day of the seminar until 12:00 (noon). This can just be one sentence. E.g., a comment that points something you liked about the paper and/or something that you would have done differently. You can also relate your discussion question to current events.</p>
<p><strong>Presentation of one paper (Pass/Fail):</strong></p>
<p>There will be short group presentations (max. 12 minutes, 3-4 people depending on the seminar size, support presentation with slides) of selected research articles beginning after the Easter break. You should be able to convey the main take-aways and core results of empirical research. But more on this during the semester!</p>
<p><strong>Submission of a research proposal (Optional):</strong></p>
<p>You have the possibility to write a research proposal developing your research question for your final term paper during the semester. It a) gives the motivation for your research question and, b) presents a short (preliminary) overview of related literature, which can already lead to hypotheses. Your term paper can be based on your proposal but does not have to. Length: 700 – 800 words (excluding references, +/- 10% , 12pt font - Times New Roman or Calibri, and 1.5 line spacing), it can be written in English or German. The proposal should be submitted as PDF via ILIAS. <strong>Deadline:</strong> April 18, 2023, 20:00. You will get detailed feedback from me. Furthermore, by opting in for the research proposal you agree to give feedback on two proposals of your peers.</p>
<p><strong>Term paper (100% of your grade):</strong></p>
<p>You will write a short term paper on the topics discussed in the seminar. You should a) identify a research question on your own, b) develop a theory (causal mechanism) and hypotheses, c) describe data and method used to answer your research question, and d) the paper should include a (preliminary/basic) empirical analysis (descriptives, correlations, basic regressions. If you want, you can also include ideas for more advanced analyses. Especially, if you choose not to write a research proposal, I recommend you to come to my office hours to discuss your topic. We will discuss in more detail on how to write a “good” term paper during the semester. The paper has to be submitted as PDF via ILIAS. The length should be around 3500 words (excluding references, +/- 10% , 12pt font - Times New Roman or Calibri, and 1.5 line spacing), can be written in English or German. Late submissions will result in deductions of 1/3 of a grade point per day. In case of any questions or problems, please get in touch with me early. More on this to come during the semester. <strong>Deadline:</strong> July 4, 2023, 20:00.</p>
</section>
<section id="recommended-readings" class="level2">
<h2 class="anchored" data-anchor-id="recommended-readings">(Recommended) Readings</h2>
<p>Helpful background readings for this seminar include the following articles:</p>
<ul>
<li><p>Bernauer, T. (2013). Climate change politics. Annual review of political science, 16, 421-448.</p></li>
<li><p>Cao, X., Milner, H. V., Prakash, A., &amp; Ward, H. (2014). Research frontiers in comparative and international environmental politics: an introduction. Comparative Political Studies, 47(3), 291-308.</p></li>
<li><p>Howe, P. D., Marlon, J. R., Mildenberger, M., &amp; Shield, B. S. (2019). How will climate change shape climate opinion?. Environmental Research Letters, 14(11).</p></li>
</ul>
<p>Furthermore, there are mandatory readings for each session. They convey the session’s the take-away message. Therefore, you should read these texts carefully. We will use <a href="https://www.perusall.com/">Perusall</a> as a tool for collaborative reading. You will find the mandatory readings on <a href="https://ilias.uni-mannheim.de/login.php?target=&amp;client_id=ILIAS&amp;auth_stat=">ILIAS</a> However, they (mostly) should be accessible via the university library (<a href="https://primo.bib.uni-mannheim.de/primo-explore/search?vid=MAN_UB&amp;lang=en_US&amp;fromRedirectFilter=true">Katalog-Primo</a>).</p>
</section>
<section id="organization-learning-resources" class="level2">
<h2 class="anchored" data-anchor-id="organization-learning-resources">Organization &amp; Learning Resources</h2>
<p><strong>Course website, Slack, and ILIAS:</strong></p>
<p>The plan is to use primarily the course website and Slack for providing the structure of the seminar and communication, respectively. Nevertheless, you will find the information on ILIAS as well. Make sure to regularly check your university e-mail address.</p>
<ul>
<li><p>You can find the course website here: <a href="https://politics-of-climate-change.netlify.app">Link</a></p></li>
<li><p>The ILIAS seminar name is: PS Einführung in die Vergleichende Regierungslehre: The Politics of Climate Change [PS] [1. PG] (FSS 2023). Ensure that you have access to the system and that e-mails sent over ILIAS are forwarded to the e-mail account you check regularly.</p></li>
<li><p>If you have contacted me with a question via any channel and you did not hear back after 2 days (except over the weekend), please just send me your question again!</p></li>
</ul>
<p><strong>Office hours:</strong></p>
<ul>
<li><p>In-person (A 340) or via Zoom, Tue, 10:15 – 11:45, please make an appointment by e-mail.</p></li>
<li><p>If you have a specific question or problem (e.g., finding a research question), please tell me before coming to the office hours (when making the appointment). This way , I can also prepare for it making it more productive and constructive.</p></li>
</ul>
<p><strong>Covid-19 (and general illness):</strong></p>
<ul>
<li>If you feel ill or have symptoms, please be considerate of your fellow students and yourself(!). Just let me know by e-mail.</li>
</ul>
<p><strong>Students with disabilities or chronic illnesses:</strong></p>
<ul>
<li><p>Please contact me or the Office of Student Affairs if you need special assistance due to disabilities or chronic illnesses.</p></li>
<li><p>And please do this early in the semester so that we can make the appropriate arrangements immediately.</p></li>
</ul>
<p><strong>If you need support:</strong></p>
<p>Of course, you can always talk directly to me if you feel comfortable with the question. It is important to note that the <a href="https://www.uni-mannheim.de/gleichstellung/beratung/">University’s Equality and Diversity Office</a> supports and advises you in cases of discrimination or sexual harassment. The responsible contact person in such a case is Dipl.-Psych. Ute Pfründer. She is trained to deal with such incidents and will keep everything strictly confidential. No action will be taken without your express consent. Further counseling services offered by the university can be found via this <a href="https://www.uni-mannheim.de/studium/beratung-und-service/beratungswegweiser/">link</a>.</p>
</section>
<section id="course-schedule" class="level2">
<h2 class="anchored" data-anchor-id="course-schedule">Course Schedule</h2>
<table class="table">
<colgroup>
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 70%">
</colgroup>
<tbody>
<tr class="odd">
<td>Session</td>
<td>Date</td>
<td>Topic</td>
</tr>
<tr class="even">
<td>1</td>
<td>14.02.2023</td>
<td>Intro Session</td>
</tr>
<tr class="odd">
<td>2</td>
<td>21.02.2023</td>
<td>The Science of Climate Change &amp; Impacts</td>
</tr>
<tr class="even">
<td>3</td>
<td>28.02.2023</td>
<td>Climate Change as Collective Action Problem?</td>
</tr>
<tr class="odd">
<td>4</td>
<td>07.03.2023</td>
<td>Public Opinion on Climate Change</td>
</tr>
<tr class="even">
<td>5</td>
<td>14.03.2023</td>
<td>Natural Disasters, Attitudes and Voting Behaviour</td>
</tr>
<tr class="odd">
<td>6</td>
<td>21.03.2023</td>
<td>Natural Disasters and Political Accountability</td>
</tr>
<tr class="even">
<td>7</td>
<td>28.03.2023</td>
<td>Success and Impact of Green Parties</td>
</tr>
<tr class="odd">
<td>-</td>
<td>04.04.2023</td>
<td>Easter Break</td>
</tr>
<tr class="even">
<td>-</td>
<td>11.04.2023</td>
<td>Easter Break</td>
</tr>
<tr class="odd">
<td>8</td>
<td>18.04.2023</td>
<td>Party Responsiveness to Climate Change</td>
</tr>
<tr class="even">
<td>9</td>
<td>25.04.2023</td>
<td>Behaviour and Polarization</td>
</tr>
<tr class="odd">
<td>10</td>
<td>02.05.2023</td>
<td>Populist Backlash</td>
</tr>
<tr class="even">
<td>11</td>
<td>09.05.2023</td>
<td>Climate Action from an International Perspective</td>
</tr>
<tr class="odd">
<td>12</td>
<td>16.05.2023</td>
<td>Climate Change and Inequality</td>
</tr>
<tr class="even">
<td>13</td>
<td>23.05.2023</td>
<td>Climate Change and Democracy</td>
</tr>
<tr class="odd">
<td>14</td>
<td>30.05.2023</td>
<td>Closing Session</td>
</tr>
</tbody>
</table>
</section>
<section id="course-schedule-and-reading-material" class="level2">
<h2 class="anchored" data-anchor-id="course-schedule-and-reading-material">Course Schedule and Reading Material</h2>
<p>The reading list will be updated from time to time. Keep an eye on announcements on Slack or ILIAS.</p>
<section id="block-i-intro" class="level3">
<h3 class="anchored" data-anchor-id="block-i-intro"><strong>BLOCK I: INTRO</strong></h3>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>1. Intro Session (February 14)</strong></p>
</div>
</div>
</div>
<ul>
<li><p>No mandatory reading</p></li>
<li><p>Seminar outline</p></li>
</ul>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>2. The Science of Climate Change &amp; Impacts (February 21)</strong></p>
</div>
</div>
</div>
<p>Mandatory Readings:</p>
<ul>
<li><p>Carleton, T. A., &amp; Hsiang, S. M. (2016). Social and economic impacts of climate. Science, 353(6304), aad9837.</p></li>
<li><p>Hsiang, S., &amp; Kopp, R. E. (2018). An economist’s guide to climate change science. Journal of Economic Perspectives, 32(4), 3-32.</p></li>
</ul>
<p>Further Readings:</p>
<ul>
<li><p>Doherty, T. J., &amp; Clayton, S. (2011). The psychological impacts of global climate change. American Psychologist, 66(4), 265.</p></li>
<li><p>Hsiang, S. M., Burke, M., &amp; Miguel, E. (2013). Quantifying the influence of climate on human conflict. Science, 341(6151), 1235367.</p></li>
<li><p>IPCC (2022). Summary for policymakers.</p></li>
<li><p>IPCC (2022). Full report.</p></li>
<li><p>The En-ROADS Climate Solutions Simulator (2022)</p></li>
</ul>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>3. Climate Change as Collective Action Problem? (February 28)</strong></p>
</div>
</div>
</div>
<p>Mandatory Readings:</p>
<ul>
<li><p>Aklin, M., &amp; Mildenberger, M. (2020). Prisoners of the wrong dilemma: why distributive conflict, not collective action, characterizes the politics of climate change. Global Environmental Politics, 20(4), 4-27.</p></li>
<li><p>Breetz, H., Mildenberger, M., &amp; Stokes, L. (2018). The political logics of clean energy transitions. Business and Politics, 20(4), 492-522.</p></li>
</ul>
<p>Further Readings:</p>
<ul>
<li><p>Hardin, G. (1968). The tragedy of the commons: the population problem has no technical solution; it requires a fundamental extension in morality. Science, 162(3859), 1243-1248.</p></li>
<li><p>Mildenberger, M. (2019). The Tragedy of the Tragedy of the Commons. Scientific American, 23. o Nordhaus, W. (2015). Climate clubs: Overcoming free-riding in international climate policy. American Economic Review, 105(4), 1339-1370.</p></li>
<li><p>Ostrom, E. (1990). Governing the commons: The evolution of institutions for collective action. Cambridge University Press.</p></li>
</ul>
</section>
<section id="block-ii-political-behaviour" class="level3">
<h3 class="anchored" data-anchor-id="block-ii-political-behaviour">BLOCK II: Political Behaviour</h3>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>4. Public Opinion on Climate Change (March 7)</strong></p>
</div>
</div>
</div>
<p>Mandatory Readings:</p>
<ul>
<li><p>Bush, S. S., &amp; Clayton, A. (2022). Facing change: Gender and climate change attitudes worldwide. American Political Science Review, 1-18.</p></li>
<li><p>Lee, T. M., Markowitz, E. M., Howe, P. D., Ko, C. Y., &amp; Leiserowitz, A. A. (2015). Predictors of public climate change awareness and risk perception around the world. Nature climate change, 5(11), 1014-1020</p></li>
</ul>
<p>Further Readings:</p>
<ul>
<li>Mildenberger, M., &amp; Leiserowitz, A. (2017). Public opinion on climate change: Is there an economy–environment tradeoff?. Environmental Politics, 26(5), 801-824.?</li>
</ul>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>5. Natural Disasters, Climate Attitudes and Voting Behaviour (March 14)</strong></p>
</div>
</div>
</div>
<p>Mandatory Readings:</p>
<ul>
<li><p>Garside, S., &amp; Zhai, H. (2022). If not now, when? Climate disaster and the Green vote following the 2021 Germany floods. Research &amp; Politics, 9(4)</p></li>
<li><p>Hilbig, H., &amp; Riaz, S. (2021). Natural Disasters and Electoral Support for Green Parties-Evidence from the 2021 Flood in Germany. OSF Preprints.</p></li>
</ul>
<p>Further Readings:</p>
<ul>
<li><p>Baccini, L., &amp; Leemann, L. (2021). Do natural disasters help the environment? How voters respond and what that means. Political Science Research and Methods, 9(3), 468-484.</p></li>
<li><p>Egan, P. J., &amp; Mullin, M. (2012). Turning personal experience into political attitudes: The effect of local weather on Americans’ perceptions about global warming. The Journal of Politics, 74(3), 796-809.</p></li>
<li><p>Hazlett, C., &amp; Mildenberger, M. (2020). Wildfire exposure increases proenvironment voting within democratic but not republican areas. American Political Science Review, 114(4), 1359-1365.</p></li>
<li><p>Quoß, F., &amp; Rudolph, L. (2022). Operationalisation matters: Weather extremes as noisy natural experiment show no influence on political attitudes. OSF Preprints.</p></li>
</ul>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>6. Natural Disasters and Political Accountability (March 21)</strong></p>
</div>
</div>
</div>
<p>Mandatory Readings:</p>
<ul>
<li><p>Gasper, J. T., &amp; Reeves, A. (2011). Make it rain? Retrospection and the attentive electorate in the context of natural disasters. American Journal of Political Science, 55(2), 340-355.</p></li>
<li><p>Healy, A., &amp; Malhotra, N. (2009). Myopic voters and natural disaster policy. American Political Science Review, 103(3), 387-406.</p></li>
</ul>
<p>Further Readings:</p>
<ul>
<li><p>Bechtel, M. M., &amp; Hainmueller, J. (2011). How lasting is voter gratitude? An analysis of the short‐and long‐term electoral returns to beneficial policy. American journal of political science, 55(4), 852-868.</p></li>
<li><p>Cole, S., Healy, A., &amp; Werker, E. (2012). Do voters demand responsive governments? Evidence from Indian disaster relief. Journal of Development Economics, 97(2), 167-181.</p></li>
</ul>
</section>
<section id="block-iii-political-parties" class="level3">
<h3 class="anchored" data-anchor-id="block-iii-political-parties">BLOCK III: Political Parties</h3>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>7. Success and Impact of Green Parties (March 28)</strong></p>
</div>
</div>
</div>
<p>Mandatory Readings:</p>
<ul>
<li><p>Abou-Chadi, T. (2016). Niche party success and mainstream party policy shifts–how green and radical right parties differ in their impact. British Journal of Political Science, 46(2), 417-436.</p></li>
<li><p>Grant, Z. P., &amp; Tilley, J. (2019). Fertile soil: explaining variation in the success of Green parties. West European Politics, 42(3), 495-516.</p></li>
</ul>
<p>Further Readings:</p>
<ul>
<li><p>Burchell, J. (2002). The Evolution of Green Politics - Development and Change within European Green Parties. London: Earthscan. Chapter 1: A ‘New’ Challenge to Party Politics? Analysing Green Party Development and Change</p></li>
<li><p>Carter, N. (2013). Greening the mainstream: party politics and the environment. Environmental Politics, 22(1), 73-94.</p></li>
<li><p>Kitschelt, H. P. (1986). Political opportunity structures and political protest: Anti-nuclear movements in four democracies. British journal of political science, 16(1), 57-85.</p></li>
<li><p>Spoon, J. J., Hobolt, S. B., &amp; De Vries, C. E. (2014). Going green: Explaining issue competition on the environment. European Journal of Political Research, 53(2), 363-380.</p></li>
</ul>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Easter Break: There are no lectures on April 4 and April 11</strong></p>
</div>
</div>
</div>
<p><strong>Optional:</strong> Research Proposal until April 18</p>
<p><strong>Pass/Fail:</strong> Group presentations start after the Easter break</p>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>8. Party Responsiveness to Climate Change (April 18)</strong></p>
</div>
</div>
</div>
<p>Mandatory Readings:</p>
<ul>
<li><p>Birch, S. (2023). The electoral benefits of environmental position‐taking: Floods and electoral outcomes in England 2010–2019. European Journal of Political Research, 62(1), 95-117.</p></li>
<li><p>Schweizer, D. (2023). No Planet B? Climate Change and Party Competition. Working Paper.</p></li>
</ul>
<p>Further Readings:</p>
<ul>
<li><p>Bernardi, L., Morales, L., Lühiste, M., &amp; Bischof, D. (2018). The effects of the Fukushima disaster on nuclear energy debates and policies: a two-step comparative examination. Environmental Politics, 27(1), 42-68.</p></li>
<li><p>Berker, L. E., &amp; Pollex, J. (2022). Explaining differences in party reactions to the Fridays for Future-movement–a qualitative comparative analysis (QCA) of parties in three European countries. Environmental Politics, 1-38.</p></li>
<li><p>Carter, N., Ladrech, R., Little, C., &amp; Tsagkroni, V. (2018). Political parties and climate policy: A new approach to measuring parties’ climate policy preferences. Party Politics, 24(6), 731-742.</p></li>
<li><p>Farstad, F. M. (2018). What explains variation in parties’ climate change salience?. Party Politics, 24(6), 698-707</p></li>
<li><p>Valentim, A. (2021). Imperfect Information and Party Responsiveness: Evidence from Extreme Weather Events and the Green Party in England. Available at SSRN 3960045.</p></li>
</ul>
</section>
<section id="block-iv-climate-policies-behaviour-and-polarization" class="level3">
<h3 class="anchored" data-anchor-id="block-iv-climate-policies-behaviour-and-polarization">BLOCK IV: Climate Policies, Behaviour, and Polarization</h3>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>9. Behaviour and Polarization (April 25)</strong></p>
</div>
</div>
</div>
<p>Mandatory Readings:</p>
<ul>
<li><p>McCright, A. M., &amp; Dunlap, R. E. (2011). The politicization of climate change and polarization in the American public’s views of global warming, 2001–2010. The Sociological Quarterly, 52(2), 155-194.</p></li>
<li><p>Otteni, C., &amp; Weisskircher, M. (2022). Global warming and polarization. Wind turbines and the electoral success of the greens and the populist radical right. European Journal of Political Research, 61(4), 1102-1122.</p></li>
</ul>
<p>Further Readings:</p>
<ul>
<li>Stokes, L. C. (2016). Electoral backlash against climate policy: A natural experiment on retrospective voting and local resistance to public policy. American Journal of Political Science, 60(4), 958-974.</li>
</ul>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>10. Populist Backlash (May 2)</strong></p>
</div>
</div>
</div>
<p>Mandatory Readings:</p>
<ul>
<li><p>Forchtner, B. (2019). Climate change and the far right. Wiley Interdisciplinary Reviews: Climate Change, 10(5), e604.</p></li>
<li><p>Huber, R. A., Fesenfeld, L., &amp; Bernauer, T. (2020). Political populism, responsiveness, and public support for climate mitigation. Climate Policy, 20(3), 373-386.</p></li>
</ul>
<p>Further Readings:</p>
<ul>
<li><p>Vihma, A., Reischl, G., &amp; Nonbo Andersen, A. (2021). A climate backlash: comparing populist parties’ climate policies in Denmark, Finland, and Sweden. The Journal of Environment &amp; Development, 30(3), 219-239.</p></li>
<li><p>Chan, G., Stavins, R., &amp; Ji, Z. (2018). International climate change policy. Annual Review of Resource Economics, 10, 335-360.</p></li>
</ul>
</section>
<section id="block-v-challenges-of-climate-change" class="level3">
<h3 class="anchored" data-anchor-id="block-v-challenges-of-climate-change">BLOCK V: Challenges of Climate Change</h3>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>11. Climate Action from an International Perspective (May 9)</strong></p>
</div>
</div>
</div>
<p>Mandatory Readings:</p>
<ul>
<li><p>Bechtel, M. M., Scheve, K. F., &amp; van Lieshout, E. (2022). Improving public support for climate action through multilateralism. Nature Communications, 13(1), 6441.</p></li>
<li><p>Harrison, K., &amp; Sundstrom, L. M. (2007). The comparative politics of climate change. Global Environmental Politics, 7(4), 1-18.</p></li>
</ul>
<p>Further Readings:</p>
<ul>
<li>Chan, G., Stavins, R., &amp; Ji, Z. (2018). International climate change policy. Annual Review of Resource Economics, 10, 335-360.</li>
</ul>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>12. Climate Change and Inequality (May 16)</strong></p>
</div>
</div>
</div>
<p>Mandatory Readings:</p>
<ul>
<li><p>Diffenbaugh, N. S., &amp; Burke, M. (2019). Global warming has increased global economic inequality. Proceedings of the National Academy of Sciences, 116(20), 9808-9813.</p></li>
<li><p>Hartzell‐Nichols, L. (2011). Responsibility for meeting the costs of adaptation. Wiley Interdisciplinary Reviews: Climate Change, 2(5), 687-700.</p></li>
</ul>
<p>Further Readings:</p>
<ul>
<li>Knox, J., Hess, T., Daccache, A., &amp; Wheeler, T. (2012). Climate change impacts on crop productivity in Africa and South Asia. Environmental research letters, 7(3).</li>
</ul>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>13. Climate Change and Democracy (May 23)</strong></p>
</div>
</div>
</div>
<p>Mandatory Readings:</p>
<ul>
<li><p>Mittiga, R. (2022). Political legitimacy, authoritarianism, and climate change. American Political Science Review, 116(3), 998-1011.</p></li>
<li><p>Schweizer, D., Menzner, J. (2023). Worried about climate change and unsatisfied with democracy? Working Paper.</p></li>
</ul>
<p>Further Readings:</p>
<ul>
<li><p>Ross, M. L. (2015). What have we learned about the resource curse?. Annual Review of Political Science, 18, 239-259.</p></li>
<li><p>Von Stein, J. (2022). Democracy, autocracy, and everything in between: How domestic institutions affect environmental protection. British Journal of Political Science, 52(1), 339-357.</p></li>
</ul>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>14. Closing Session (May 30)</strong></p>
</div>
</div>
</div>
<ul>
<li><p>No mandatory reading</p></li>
<li><p>Wrap-up, seminar evaluation, and discussion of research designs</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">The Politics of Climate Change | Spring 2023 | University of Mannheim</div>   
    <div class="nav-footer-right">This page is built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



</body></html>